id = "catbox"
name = "Catbox theme"
version = "0.0.1"
schema_version = 1
authors = ["Adib Hanna<adibhanna@gmail.com>"]
description = "Gruvbox-inspired theme for Zed"
repository = "https://github.com/adibhanna/catbox"
